In [3]:
!pip install gensim

import nltk
nltk.download('punkt')

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

sentences = [
    "I love AI",
    "AI is future",
    "I love learning"
]





[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [4]:
# 1. Bag of Words

bow_vectorizer = CountVectorizer()
bow = bow_vectorizer.fit_transform(sentences)

print("Bag of Words Vocabulary:")
print(bow_vectorizer.get_feature_names_out())

print("\nBag of Words Matrix:")
print(bow.toarray())

Bag of Words Vocabulary:
['ai' 'future' 'is' 'learning' 'love']

Bag of Words Matrix:
[[1 0 0 0 1]
 [1 1 1 0 0]
 [0 0 0 1 1]]


In [5]:
# 2. Normalized Count
import numpy as np

bow_array = bow.toarray()
normalized_bow = bow_array / bow_array.sum(axis=1, keepdims=True)

print("\nNormalized Bag of Words:")
print(normalized_bow)


Normalized Bag of Words:
[[0.5        0.         0.         0.         0.5       ]
 [0.33333333 0.33333333 0.33333333 0.         0.        ]
 [0.         0.         0.         0.5        0.5       ]]


In [6]:
# 3. TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf = tfidf_vectorizer.fit_transform(sentences)

print("\nTF-IDF Matrix:")
print(tfidf.toarray())



TF-IDF Matrix:
[[0.70710678 0.         0.         0.         0.70710678]
 [0.4736296  0.62276601 0.62276601 0.         0.        ]
 [0.         0.         0.         0.79596054 0.60534851]]


In [7]:
# 4. Word2Vec Embeddings
# Convert sentences into word lists
tokenized_sentences = [sentence.lower().split() for sentence in sentences]

model = Word2Vec(tokenized_sentences, vector_size=50, min_count=1)

print("\nWord2Vec Vector for 'ai':")
print(model.wv['ai'])


Word2Vec Vector for 'ai':
[-1.0724545e-03  4.7286271e-04  1.0206699e-02  1.8018546e-02
 -1.8605899e-02 -1.4233618e-02  1.2917745e-02  1.7945977e-02
 -1.0030856e-02 -7.5267432e-03  1.4761009e-02 -3.0669428e-03
 -9.0732267e-03  1.3108104e-02 -9.7203208e-03 -3.6320353e-03
  5.7531595e-03  1.9837476e-03 -1.6570430e-02 -1.8897636e-02
  1.4623532e-02  1.0140524e-02  1.3515387e-02  1.5257311e-03
  1.2701781e-02 -6.8107317e-03 -1.8928028e-03  1.1537147e-02
 -1.5043275e-02 -7.8722071e-03 -1.5023164e-02 -1.8600845e-03
  1.9076237e-02 -1.4638334e-02 -4.6675373e-03 -3.8754821e-03
  1.6154874e-02 -1.1861792e-02  9.0324880e-05 -9.5074680e-03
 -1.9207101e-02  1.0014586e-02 -1.7519170e-02 -8.7836506e-03
 -7.0199967e-05 -5.9236289e-04 -1.5322480e-02  1.9229487e-02
  9.9641159e-03  1.8466286e-02]
